### ISSUE TITLE
关联集群后wayne崩溃

### ISSUE THREAD

**Issue by YanbingW** [Qihoo360/wayne#529]
**Describe the bug**
下载了最新版的代码，开发者模式编译，成功以后关联集群，然后报如下错误：

E1210 19:07:34.596242   29646 runtime.go:78] Observed a panic: "assignment to entry in nil map" (assignment to entry in nil map)
goroutine 29 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x178c520, 0x1c092c0)
        /root/workspaces/gopath/src/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xaa
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /root/workspaces/gopath/src/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x178c520, 0x1c092c0)
        /root/go/go/src/runtime/panic.go:513 +0x1b9
k8s.io/client-go/tools/clientcmd/api/v1.Convert_Slice_v1_NamedCluster_To_Map_string_To_Pointer_api_Cluster(0xc0005d0300, 0xc0001068d0, 0x1c37080, 0xc0003ee1e0, 0x0, 0x0)
        /root/workspaces/gopath/src/k8s.io/client-go/tools/clientcmd/api/v1/conversion.go:35 +0x1e9
k8s.io/client-go/tools/clientcmd/api/v1.autoConvert_v1_Config_To_api_Config(0xc0005d02c0, 0xc0001068a0, 0x1c37080, 0xc0003ee1e0, 0xcc32b98567ddc101, 0xc0008cd558)
        /root/workspaces/gopath/src/k8s.io/client-go/tools/clientcmd/api/v1/zz_generated.conversion.go:273 +0xa0
k8s.io/client-go/tools/clientcmd/api/v1.Convert_v1_Config_To_api_Config(0xc0005d02c0, 0xc0001068a0, 0x1c37080, 0xc0003ee1e0, 0x16212b0, 0xc0003a43f0)
        /root/workspaces/gopath/src/k8s.io/client-go/tools/clientcmd/api/v1/zz_generated.conversion.go:291 +0x49
k8s.io/client-go/tools/clientcmd/api/v1.RegisterConversions.func7(0x182c000, 0xc0005d02c0, 0x182bf40, 0xc0001068a0, 0x1c37080, 0xc0003ee1e0, 0x203000, 0xc000555200)
        /root/workspaces/gopath/src/k8s.io/client-go/tools/clientcmd/api/v1/zz_generated.conversion.go:69 +0x6f
k8s.io/apimachinery/pkg/conversion.(*Converter).doConversion(0xc0000d2180, 0x182c000, 0xc0005d02c0, 0x182bf40, 0xc0001068a0, 0x0, 0xc000110e00, 0xc0008cd738, 0x5f00000000000020, 0x1807ee0)
        /root/workspaces/gopath/src/k8s.io/apimachinery/pkg/conversion/converter.go:498 +0x6d4
k8s.io/apimachinery/pkg/conversion.(*Converter).Convert(0xc0000d2180, 0x182c000, 0xc0005d02c0, 0x182bf40, 0xc0001068a0, 0x0, 0xc000110e00, 0x1c18400, 0xc0001068a0)
        /root/workspaces/gopath/src/k8s.io/apimachinery/pkg/conversion/converter.go:470 +0x9d
k8s.io/apimachinery/pkg/runtime.(*Scheme).convertToVersion(0xc0002f75e0, 0xc0008cdc01, 0x1c18480, 0xc0005d0210, 0x1c19b80, 0xc000110de0, 0x2b93ba0, 0xc000110de0, 0xc000110de0, 0x189c5a0)
        /root/workspaces/gopath/src/k8s.io/apimachinery/pkg/runtime/scheme.go:566 +0xa10
k8s.io/apimachinery/pkg/runtime.(*Scheme).ConvertToVersion(0xc0002f75e0, 0x1c18480, 0xc0005d0210, 0x1c19b80, 0xc000110de0, 0x0, 0x0, 0xc000935d00, 0x40d91f)
        /root/workspaces/gopath/src/k8s.io/apimachinery/pkg/runtime/scheme.go:486 +0x5f
github.com/Qihoo360/wayne/src/backend/client.buildClient(0xc0004c8f00, 0xc, 0xc0005c2800, 0x1563, 0x0, 0x0, 0x2, 0x2)
        /root/workspaces/gopath/src/github.com/Qihoo360/wayne/src/backend/client/client.go:195 +0x1d7
github.com/Qihoo360/wayne/src/backend/client.BuildApiserverClient()
        /root/workspaces/gopath/src/github.com/Qihoo360/wayne/src/backend/client/client.go:69 +0x21b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0x1a949a8)
        /root/workspaces/gopath/src/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x1a949a8, 0x12a05f200, 0x0, 0x1, 0xc000340060)
        /root/workspaces/gopath/src/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xbe
k8s.io/apimachinery/pkg/util/wait.Until(0x1a949a8, 0x12a05f200, 0xc000340060)
        /root/workspaces/gopath/src/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
k8s.io/apimachinery/pkg/util/wait.Forever(0x1a949a8, 0x12a05f200)
        /root/workspaces/gopath/src/k8s.io/apimachinery/pkg/util/wait/wait.go:79 +0x41
created by github.com/Qihoo360/wayne/src/backend/initial.InitClient
        /root/workspaces/gopath/src/github.com/Qihoo360/wayne/src/backend/initial/client.go:13 +0x50
panic: assignment to entry in nil map [recovered]
        panic: assignment to entry in nil map

goroutine 29 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /root/workspaces/gopath/src/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x108
panic(0x178c520, 0x1c092c0)
        /root/go/go/src/runtime/panic.go:513 +0x1b9
k8s.io/client-go/tools/clientcmd/api/v1.Convert_Slice_v1_NamedCluster_To_Map_string_To_Pointer_api_Cluster(0xc0005d0300, 0xc0001068d0, 0x1c37080, 0xc0003ee1e0, 0x0, 0x0)
        /root/workspaces/gopath/src/k8s.io/client-go/tools/clientcmd/api/v1/conversion.go:35 +0x1e9
k8s.io/client-go/tools/clientcmd/api/v1.autoConvert_v1_Config_To_api_Config(0xc0005d02c0, 0xc0001068a0, 0x1c37080, 0xc0003ee1e0, 0xcc32b98567ddc101, 0xc0008cd558)
        /root/workspaces/gopath/src/k8s.io/client-go/tools/clientcmd/api/v1/zz_generated.conversion.go:273 +0xa0
k8s.io/client-go/tools/clientcmd/api/v1.Convert_v1_Config_To_api_Config(0xc0005d02c0, 0xc0001068a0, 0x1c37080, 0xc0003ee1e0, 0x16212b0, 0xc0003a43f0)
        /root/workspaces/gopath/src/k8s.io/client-go/tools/clientcmd/api/v1/zz_generated.conversion.go:291 +0x49
k8s.io/client-go/tools/clientcmd/api/v1.RegisterConversions.func7(0x182c000, 0xc0005d02c0, 0x182bf40, 0xc0001068a0, 0x1c37080, 0xc0003ee1e0, 0x203000, 0xc000555200)
        /root/workspaces/gopath/src/k8s.io/client-go/tools/clientcmd/api/v1/zz_generated.conversion.go:69 +0x6f
k8s.io/apimachinery/pkg/conversion.(*Converter).doConversion(0xc0000d2180, 0x182c000, 0xc0005d02c0, 0x182bf40, 0xc0001068a0, 0x0, 0xc000110e00, 0xc0008cd738, 0x5f00000000000020, 0x1807ee0)
        /root/workspaces/gopath/src/k8s.io/apimachinery/pkg/conversion/converter.go:498 +0x6d4
k8s.io/apimachinery/pkg/conversion.(*Converter).Convert(0xc0000d2180, 0x182c000, 0xc0005d02c0, 0x182bf40, 0xc0001068a0, 0x0, 0xc000110e00, 0x1c18400, 0xc0001068a0)
        /root/workspaces/gopath/src/k8s.io/apimachinery/pkg/conversion/converter.go:470 +0x9d
k8s.io/apimachinery/pkg/runtime.(*Scheme).convertToVersion(0xc0002f75e0, 0xc0008cdc01, 0x1c18480, 0xc0005d0210, 0x1c19b80, 0xc000110de0, 0x2b93ba0, 0xc000110de0, 0xc000110de0, 0x189c5a0)
        /root/workspaces/gopath/src/k8s.io/apimachinery/pkg/runtime/scheme.go:566 +0xa10
k8s.io/apimachinery/pkg/runtime.(*Scheme).ConvertToVersion(0xc0002f75e0, 0x1c18480, 0xc0005d0210, 0x1c19b80, 0xc000110de0, 0x0, 0x0, 0xc000935d00, 0x40d91f)
        /root/workspaces/gopath/src/k8s.io/apimachinery/pkg/runtime/scheme.go:486 +0x5f
github.com/Qihoo360/wayne/src/backend/client.buildClient(0xc0004c8f00, 0xc, 0xc0005c2800, 0x1563, 0x0, 0x0, 0x2, 0x2)
        /root/workspaces/gopath/src/github.com/Qihoo360/wayne/src/backend/client/client.go:195 +0x1d7
github.com/Qihoo360/wayne/src/backend/client.BuildApiserverClient()
        /root/workspaces/gopath/src/github.com/Qihoo360/wayne/src/backend/client/client.go:69 +0x21b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0x1a949a8)
        /root/workspaces/gopath/src/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x1a949a8, 0x12a05f200, 0x0, 0x1, 0xc000340060)
        /root/workspaces/gopath/src/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xbe
k8s.io/apimachinery/pkg/util/wait.Until(0x1a949a8, 0x12a05f200, 0xc000340060)
        /root/workspaces/gopath/src/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
k8s.io/apimachinery/pkg/util/wait.Forever(0x1a949a8, 0x12a05f200)
        /root/workspaces/gopath/src/k8s.io/apimachinery/pkg/util/wait/wait.go:79 +0x41
created by github.com/Qihoo360/wayne/src/backend/initial.InitClient
        /root/workspaces/gopath/src/github.com/Qihoo360/wayne/src/backend/initial/client.go:13 +0x50

**To Reproduce**

**Expected behavior**
系统瘫痪，8080端口也不在监听状态

**Desktop (please complete the following information):**

**Server Version**
```
- Dashboard version: 无
- Kubernetes version: 开发者，不涉及k8s
- Wayne version: 最新版代码
- Node.js version:  
- Go version: go1.11.5
```

**Comment by YanbingW** [comment]
究竟哪个版本的代码可以正常使用，请告知

**Comment by YanbingW** [comment]
现在怀疑和k8s的依赖包的版本有关，能公布一下各个依赖包的版本吗

**Comment by YanbingW** [comment]
问题终于解决了，因为k8s.io包版本不匹配的问题
