### ISSUE TITLE
File to import not found or unreadable: bootstrap/scss/normalize

### ISSUE THREAD

**Issue by coollhg** [Qihoo360/wayne#54]
```
➜  frontend git:(master) ✗ cnpm run build

> frontend@1.0.1 build /GOPATH/src/github.com/Qihoo360/wayne/src/frontend
> node --max_old_space_size=4096 ./node_modules/@angular/cli/bin/ng build --aot --prod --build-optimizer --base-href "/public/"


Date: 2018-11-22T15:38:20.305Z
Hash: e85553e8979192228377
Time: 10662ms
chunk {scripts} scripts.481127d91ac897bf144f.js (scripts) 627 kB  [rendered]
chunk {0} runtime.a66f828dca56eeb90e02.js (runtime) 1.05 kB [entry] [rendered]
chunk {1} styles.557610e77b32cb6cb9c8.css (styles) 13.1 kB [initial] [rendered]
chunk {2} polyfills.e7f5364b276024e19b0b.js (polyfills) 130 bytes [initial] [rendered]
chunk {3} main.0594610c91de797f492a.js (main) 128 bytes [initial] [rendered]

ERROR in ./src/theme/theme.scss
Module build failed: ModuleBuildError: Module build failed:
@import 'bootstrap/scss/normalize';
^
      File to import not found or unreadable: bootstrap/scss/normalize.
      in /GOPATH/src/github.com/Qihoo360/wayne/src/frontend/node_modules/@clr/ui/src/utils/_dependencies.clarity.scss (line 11, column 1)
    at runLoaders (/GOPATH/src/github.com/Qihoo360/wayne/src/frontend/node_modules/webpack/lib/NormalModule.js:252:20)
    at /GOPATH/src/github.com/Qihoo360/wayne/src/frontend/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /GOPATH/src/github.com/Qihoo360/wayne/src/frontend/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/GOPATH/src/github.com/Qihoo360/wayne/src/frontend/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.render [as callback] (/GOPATH/src/github.com/Qihoo360/wayne/src/frontend/node_modules/sass-loader/lib/loader.js:52:13)
    at Object.done [as callback] (/GOPATH/src/github.com/Qihoo360/wayne/src/frontend/node_modules/neo-async/async.js:8077:18)
    at options.error (/GOPATH/src/github.com/Qihoo360/wayne/src/frontend/node_modules/node-sass/lib/index.js:294:32)
ERROR in app/portal/portal.module.ts(57,5): Error during template compile of 'PortalModule'
  Could not resolve ../../../lib/portal/library-portal.module relative to /GOPATH/src/github.com/Qihoo360/wayne/src/frontend/src/app/portal/portal.module.ts..
src/app/portal/portal-routing.module.ts(32,28): error TS2307: Cannot find module '../../../lib/portal/library-routing-portal'.
src/app/portal/portal.module.ts(32,35): error TS2307: Cannot find module '../../../lib/portal/library-portal.module'.
src/app/admin/admin-routing.module.ts(54,27): error TS2307: Cannot find module '../../../lib/admin/library-routing-admin'.
src/app/admin/admin.module.ts(36,34): error TS2307: Cannot find module '../../../lib/admin/library-admin.module'.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frontend@1.0.1 build: `node --max_old_space_size=4096 ./node_modules/@angular/cli/bin/ng build --aot --prod --build-optimizer --base-href "/public/"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the frontend@1.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by wilhelmguo** [comment]
Please use npm instead cnpm
