### ISSUE TITLE
docker-compose启动报错，panic: Exception (501) Reason: "read tcp  : read: connection reset by peer"

### ISSUE THREAD

**Issue by qinlz-1** [Qihoo360/wayne#624]
docker-compose.yaml：
version: '2'
services:
  rabbitmq:
    environment:
      RABBITMQ_NODENAME: "rabbit"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    image: rabbitmq:3.7.8-management
    networks:
    - default
    ports:
    - "5672:5672"
  wayne:
    image: 360cloud/wayne:latest
    command: /opt/wayne/backend apiserver
    environment:
      GOPATH: "/go"
    volumes:
      - ./src/backend/conf:/opt/wayne/conf:z
      - ./cert:/data/cert:z
      - /tmp/wayne_logs:/tmp:z
    networks:
      - default
    expose:
      - "8080"
    ports:
      - "8080:8080"
报错日志：
wayne_1     | panic: Exception (501) Reason: "read tcp 172.18.0.3:41126->10.52.254.233:5672: read: connection reset by peer"
wayne_1     | 
wayne_1     | goroutine 1 [running]:
wayne_1     | github.com/Qihoo360/wayne/src/backend/initial.InitBus()
wayne_1     |   /go/src/github.com/Qihoo360/wayne/src/backend/initial/bus.go:13 +0xb3
wayne_1     | github.com/Qihoo360/wayne/src/backend/cmd/apiserver.run(0x28b2e00, 0x28e04e0, 0x0, 0x0)
wayne_1     |   /go/src/github.com/Qihoo360/wayne/src/backend/cmd/apiserver/apiserver.go:38 +0xb1
wayne_1     | github.com/spf13/cobra.(*Command).execute(0x28b2e00, 0x28e04e0, 0x0, 0x0, 0x28b2e00, 0x28e04e0)
wayne_1     |   /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2ae
wayne_1     | github.com/spf13/cobra.(*Command).ExecuteC(0x28b2940, 0x146a0c9, 0xc0002eff88, 0xc0000a6058)
wayne_1     |   /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ec
wayne_1     | github.com/spf13/cobra.(*Command).Execute(...)
wayne_1     |   /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
wayne_1     | main.main()
wayne_1     |   /go/src/github.com/Qihoo360/wayne/src/backend/main.go:12 +0x50
wayne_wayne_1 exited with code 2
rabbitmq_1  | 2024-07-10 05:13:02.452 [info] <0.33.0> Application lager started on node rabbit@9b76a2b3230e
rabbitmq_1  | 2024-07-10 05:13:05.039 [info] <0.33.0> Application crypto started on node rabbit@9b76a2b3230e
rabbitmq_1  | 2024-07-10 05:13:05.039 [info] <0.33.0> Application cowlib started on node rabbit@9b76a2b3230e
rabbitmq_1  | 2024-07-10 05:13:05.040 [info] <0.33.0> Application xmerl started on node rabbit@9b76a2b3230e
rabbitmq_1  | 2024-07-10 05:13:05.040 [info] <0.33.0> Application os_mon started on node rabbit@9b76a2b3230e
rabbitmq_1  | 2024-07-10 05:13:05.040 [info] <0.33.0> Application inets started on node rabbit@9b76a2b3230e
rabbitmq_1  | 2024-07-10 05:13:05.063 [info] <0.33.0> Application mnesia started on node rabbit@9b76a2b3230e
rabbitmq_1  | 2024-07-10 05:13:05.064 [info] <0.33.0> Application jsx started on node rabbit@9b76a2b3230e
rabbitmq_1  | 2024-07-10 05:13:05.064 [info] <0.33.0> Application recon started on node rabbit@9b76a2b3230e
rabbitmq_1  | 2024-07-10 05:13:05.064 [info] <0.33.0> Application asn1 started on node rabbit@9b76a2b3230e
rabbitmq_1  | 2024-07-10 05:13:05.064 [info] <0.33.0> Application public_key started on node rabbit@9b76a2b3230e
rabbitmq_1  | 2024-07-10 05:13:05.064 [info] <0.33.0> Application ssl started on node rabbit@9b76a2b3230e
rabbitmq_1  | 2024-07-10 05:13:05.065 [info] <0.33.0> Application ranch started on node rabbit@9b76a2b3230e
rabbitmq_1  | 2024-07-10 05:13:05.065 [info] <0.33.0> Application ranch_proxy_protocol started on node rabbit@9b76a2b3230e
rabbitmq_1  | 2024-07-10 05:13:05.070 [info] <0.33.0> Application cowboy started on node rabbit@9b76a2b3230e
rabbitmq_1  | 2024-07-10 05:13:05.070 [info] <0.33.0> Application rabbit_common started on node rabbit@9b76a2b3230e
rabbitmq_1  | 2024-07-10 05:13:05.071 [info] <0.221.0> 
rabbitmq_1  |  Starting RabbitMQ 3.7.8 on Erlang 20.3.8.5
rabbitmq_1  |  Copyright (C) 2007-2018 Pivotal Software, Inc.
rabbitmq_1  |  Licensed under the MPL.  See http://www.rabbitmq.com/
rabbitmq_1  | 
rabbitmq_1  |   ##  ##
rabbitmq_1  |   ##  ##      RabbitMQ 3.7.8. Copyright (C) 2007-2018 Pivotal Software, Inc.
rabbitmq_1  |   ##########  Licensed under the MPL.  See http://www.rabbitmq.com/
rabbitmq_1  |   ######  ##
rabbitmq_1  |   ##########  Logs: <stdout>
rabbitmq_1  | 
rabbitmq_1  |               Starting broker...
rabbitmq_1  | 2024-07-10 05:13:05.072 [info] <0.221.0> 
rabbitmq_1  |  node           : rabbit@9b76a2b3230e
rabbitmq_1  |  home dir       : /var/lib/rabbitmq
rabbitmq_1  |  config file(s) : /etc/rabbitmq/rabbitmq.conf
rabbitmq_1  |  cookie hash    : BEptVjPwWk4en/8EnwRIxQ==
rabbitmq_1  |  log(s)         : <stdout>
rabbitmq_1  |  database dir   : /var/lib/rabbitmq/mnesia/rabbit
rabbitmq_1  | 2024-07-10 05:13:05.325 [info] <0.227.0> Memory high watermark set to 12804 MiB (13426532352 bytes) of 32011 MiB (33566330880 bytes) total
rabbitmq_1  | 2024-07-10 05:13:05.330 [info] <0.229.0> Enabling free disk space monitoring
rabbitmq_1  | 2024-07-10 05:13:05.330 [info] <0.229.0> Disk free limit set to 50MB
rabbitmq_1  | 2024-07-10 05:13:05.333 [info] <0.232.0> Limiting to approx 1048476 file handles (943626 sockets)
rabbitmq_1  | 2024-07-10 05:13:05.333 [info] <0.233.0> FHC read buffering:  OFF
rabbitmq_1  | 2024-07-10 05:13:05.334 [info] <0.233.0> FHC write buffering: ON
rabbitmq_1  | 2024-07-10 05:13:05.341 [error] <0.220.0> CRASH REPORT Process <0.220.0> with 0 neighbours exited with reason: {{failed_to_cluster_with,[rabbit@60cc085cac37],"Mnesia could not connect to any nodes."},{rabbit,start,[normal,[]]}} in application_master:init/4 line 134
rabbitmq_1  | 2024-07-10 05:13:05.341 [info] <0.33.0> Application rabbit exited with reason: {{failed_to_cluster_with,[rabbit@60cc085cac37],"Mnesia could not connect to any nodes."},{rabbit,start,[normal,[]]}}
rabbitmq_1  | {"Kernel pid terminated",application_controller,"{application_start_failure,rabbit,{{failed_to_cluster_with,[rabbit@60cc085cac37],\"Mnesia could not connect to any nodes.\"},{rabbit,start,[normal,[]]}}}"}
rabbitmq_1  | Kernel pid terminated (application_controller) ({application_start_failure,rabbit,{{failed_to_cluster_with,[rabbit@60cc085cac37],"Mnesia could not connect to any nodes."},{rabbit,start,[normal,[]]}}})
rabbitmq_1  | 
rabbitmq_1  | Crash dump is being written to: /var/log/rabbitmq/erl_crash.dump...done
wayne_rabbitmq_1 exited with code 0

**Comment by motecshine** [comment]
高版本的 rabbitmq guest 只允许localhost 链接, 如果是docker的话 得注入rabbitmq env
